       78  MODULE-NAME         VALUE "SANDWICH REGISTRATION".
       78  MAIN-MENU-OPTION1   VALUE "1 - REGISTER SANDWICHES".
       78  MAIN-MENU-OPTION2   VALUE "2 - VIEW SANDWICHES".
       78  MAIN-MENU-CHOICE    VALUE "PLEASE CHOOSE AN OPTION".
       78  MAIN-MENU-ERROR     VALUE "INVALID OPTION, PLEASE SELECT A VA
      -    "LID OPTION. PRESS ANY KEY TO CONTINUE".
       78  LEAVE-MESSAGE       VALUE "LEAVING PROGRAM!".
       78  LEAVE-THANKS        VALUE "THANK YOU!".
