       78  MODULE-NAME     VALUE "REGISTO DE SANDUICHES".
       78  MAIN-MENU-OPTION1   VALUE "1 - REGISTAR SANDUICHES".
       78  MAIN-MENU-OPTION2   VALUE "2 - CONSULTAR SANDUICHES".
       78  MAIN-MENU-CHOICE    VALUE "POR FAVOR ESCOLHA UMA OPCAO".
       78  MAIN-MENU-ERROR     VALUE "OPCAO INVALIDA. POR FAVOR ESCOLHA
      -    " UMA OPCAO VALIDA. PRESSIONE QUALQUER TECLA PARA CONTINUAR".
       78  LEAVE-MESSAGE       VALUE "A SAIR DO PROGRAMA!".
       78  LEAVE-THANKS        VALUE "OBRIGADO!".
