@startuml CALENDAR MANAGEMENT
START 
:CALENDAR MANAGEMENT;
IF (FXCALENDAR EXISTS?) THEN (<COLOR:RED>NO)
    :CREATE FILE;
ELSE (<COLOR:GREEN>YES)
ENDIF
WHILE (CONTINUE = "Y"?) IS (<COLOR:GREEN>YES)
    : 1 - ADD DOWNTIME
     2 - UPDATE DOWNTIME
     3 - REMOVE DOWNTIME
     4 - VIEW DOWNTIME
     OTHER - EXIT;
    IF (OPTION = 1) THEN (YES)
        :ADD DOWNTIME;
    ELSEIF (OPTION = 2) THEN (YES)
        :UPDATE DOWNTIME;
    ELSEIF (OPTION = 3) THEN (YES)
        :REMOVE DOWNTIME;
        note right
            • IN CASE THE DOWNTIME
              WILL NOT OCCUR BY ANY
              REASON.

            • THE DOWNTIME IS DELETED
              FROM FXCALENDAR FILE.
        end note
    ELSEIF (OPTION = 4) THEN (<COLOR:GREEN>YES)
        :VIEW DOWNTIME;
    ELSE (<COLOR:RED>OTHER)
        :CONTINUAR = "N";
    ENDIF
ENDWHILE (<COLOR:RED>NO)
:FIM;
STOP
@enduml