@startuml
header
UpSkillCobol Breadwitch
endheader

title \nDeliciousSandwich\n
/' This is a Logical data model - see the level of details '/

entity Schools {
  * InternalId
  * ExternalId
  * Designation
  * Address
  * Active
}

entity Ingredients {
  * InternalID
  * Designation
  * Active
}

entity Suppliers {
  * SupplierID
  * CompanyName
  * CompanyAdress
  * CompanyEmail1
  * CompanyEmail2
  * CompanyEmail3
  * CompanyTelephone1
  * CompanyTelephone2
  * CompanyTelephone3
  * CompanyDescription
  * Active
}

entity Categories {
  * InternalID
  * Description
  * Active
}

entity Calendar {
  * InternalID
  * BlackoutStartDate
  * BlackoutEndDate
}

@enduml