@startuml Suppliers Management
:SUPPLIER MANAGEMENT;
IF (FXSUPPLY EXISTS?) THEN (<COLOR:RED>NO)
    :CREATE FILE;
ELSE (<COLOR:GREEN>YES)
ENDIF
WHILE (CONTINUE = "Y"?) IS (<COLOR:GREEN>YES)
    : 1 - ADD SUPPLIERS FROM FILE
     2 - ADD SUPPLIERS MANUALLY
     3 - MODIFY SUPPLIER
     4 - DELETE SUPPLIER
     5 - VIEW SUPPLIER
     OTHER - EXIT;
    IF (OPTION = 1) THEN (<COLOR:GREEN>YES)
        :OPEN SUPPLIER FILE;
        WHILE (END OF FILE?) IS (<COLOR:RED>NO)
            :READ NEXT RECORD;
            IF (VALID RECORD?) THEN (<COLOR:GREEN>YES)
                #PALEGREEN:WRITE RECORD TO FXSUPPLY;
            ELSE (<COLOR:RED>NO)
                #PINK:WRITE ERROR TO LOGFILE;
            ENDIF
        ENDWHILE (<COLOR:GREEN>YES)
    ELSEIF (OPTION = 2) THEN (<COLOR:GREEN>YES)
        :MANUALLY ADD SUPLLIER;
    ELSEIF (OPTION = 3) THEN (<COLOR:GREEN>YES)
        :MODIFY SUPLLIER;
    ELSEIF (OPTION = 4) THEN (<COLOR:GREEN>YES)
        :DELETE SUPLLIER;
        note right
            THE SUPLLIERS ARE NOT
            DELETED FROM FXSUPLLY.
            THEY ARE JUST FLAGGED
            AND CANT BE USED AFTER.
        end note
    ELSEIF (OPTION = 5) THEN (<COLOR:GREEN>YES)
        :VIEW SUPLLIER;
    ELSE (<COLOR:RED>OUTRO)
        :CONTINUE = "N";
    ENDIF
ENDWHILE (<COLOR:RED>NO)
:END;
stop
@enduml