@startuml
header
UpSkillCobol Breadwitch
endheader

title \nDeliciousSandwich\n
/' This is a Logical data model - see the level of details '/

entity Schools {
  * InternalId
  * ExternalId
  * Designation
  * Address
}

entity Ingredients {
  * InternalID
  * Designation
}

entity Suppliers {
  * SupplierID
  * CompanyName
  * CompanyDescription
  * CompanyAdress
  * CompanyEmail(s)
  * CompanyTelephone(s)
}

entity Categories {
  * InternalID
  * Description
}

entity Calendar {
  * InternalID
  * BlackoutStartDate
  * BlackoutEndDate
}

@enduml