@startuml
:SCHOOL MANAGEMENT;
if (FXSCHOOL EXISTS) equals (<color:green>YES) then
else (<color:red>NO)
:CREATE FILE;
endif
WHILE (CONTINUE) IS (<color:green>YES)

:OPTION
1 - ADD SCHOOL FROM FILE
2 - ADD SCHOOL MANUALLY
3 - MODIFY SCHOOL
4 - DELETE SCHOOL
5 - VIEW SCHOOL
OTHER - LEAVE;
IF (OPTION = 1) then
 :OPEN FILE;
if (END OF FILE) THEN (<color:green>YES)
ELSE (<color:red>NO)
:READ NEXT RECORD;
endif
IF (VALID RECORD) THEN (<color:green>YES)
#PALEGREEN:WRITE RECORD TO FXSCHOOL;
ELSE (<color:red>NO)
#PINK:WRITE ERROR TO LOGFILE;
endif
ELSEIF (OPTION = 2) THEN
:ADD SCHOOL MANUALLY;
ELSEIF (OPTION = 3) THEN
:MODIFY SCHOOL;
ELSEIF (OPTION = 4) THEN
:DELETESCHOOL;
note right
  SCHOOLS ARENT DELETED
  FROM FXSCHOOL THEY
  ARE FLAGGED AND CANT
  BE USED AFTER
end note
ELSEIF (OPTION = 5) THEN
:VIEW SCHOOL;
ELSEIF (OPTION = OTHER) THEN
:CONTINUE = <color:red>NO;
ENDIF
ENDWHILE (<color:red>NO)
:END;
STOP
@enduml