@startuml CALENDAR MANAGEMENT
START 
:CALENDAR MANAGEMENT;
IF (FXCALENDAR EXISTS?) THEN (<COLOR:RED>NO)
    :CREATE FILE;
ELSE (<COLOR:GREEN>YES)
ENDIF
    : 1 - REGISTER DOWNTIME
     2 - VIEW DOWNTIME
     3 - EDIT DOWNTIME
     4 - DELETE DOWNTIME
     5 - REPORTS

     6 - EXIT;
REPEAT
    IF (OPTION = 1) THEN (YES)
        :REGISTER DOWNTIME;
    ELSEIF (OPTION = 2) THEN (YES)
        :VIEW DOWNTIME;
    ELSEIF (OPTION = 3) THEN (YES)
        :EDIT DOWNTIME;
        
    ELSEIF (OPTION = 4) THEN (<COLOR:GREEN>YES)
        :DELETE DOWNTIME;
        note right
            • IN CASE THE DOWNTIME
              WILL NOT OCCUR BY ANY
              REASON.

            • THE DOWNTIME IS DELETED
              FROM FXCALENDAR FILE.
        end note
    ELSEIF (OPTION = 5) THEN (<COLOR:GREEN>YES)
        :REPORTS;
    ELSEIF (OPTION = 6) THEN (<COLOR:GREEN>YES)
        :END;
STOP
    ENDIF

@enduml