@startuml REGISTRATION OF SANDWICH ORDERS
START 
:REGISTRATION OF SUPPLIERS INGREDIENTS;
IF (FX EXISTS?) THEN (<COLOR:RED>NO)
    :CREATE FILE;
ELSE (<COLOR:GREEN>YES)
ENDIF
:1 - REGISTER SIPPLIERS
2 - SEARCH SUPPLIERS
3 - CREATE REPORT
4 - EXIT;
REPEAT
IF (OPTION = 1) THEN (<COLOR:GREEN>YES)
    :REGISTER SIPPLIERS;
    (<COLOR:RED>NO) ELSEIF (OPTION = 2) THEN (<COLOR:GREEN>YES)
        :SEARCH SUPPLIERS;
    (<COLOR:RED>NO) ELSEIF (OPTION = 3) THEN (<COLOR:GREEN>YES)
        :CREATE REPORT; 
    (<COLOR:RED>NO) ELSEIF (OPTION = 4) THEN (<COLOR:GREEN>YES)
        :EXIT;
        STOP
    ELSE (<COLOR:RED>NO)
ENDIF
@enduml