@startuml
START 
:SANDWICH REGISTRATION;
IF (FX EXISTS?) THEN (<COLOR:RED>NO)
    :CREATE FILE;
ELSE (<COLOR:GREEN>YES)
ENDIF
:1 - REGISTER SANDWICH
2 - SEARCH SANDWICH
3 - CREATE REPORT
4 - EXIT;
REPEAT
IF (OPTION = 1) THEN (<COLOR:GREEN>YES)
    :REGISTER SANDWICH;
    ELSEIF (OPTION = 2) THEN (<COLOR:GREEN>YES)
        :SEARCH SANDWICH;
    ELSEIF (OPTION = 3) THEN (<COLOR:GREEN>YES)
        :CREATE REPORT; 
    ELSEIF (OPTION = 4) THEN (<COLOR:GREEN>YES)
        :EXIT;
        STOP
    ELSE
ENDIF
@enduml