@startuml
START 
:INVENTORY MANAGEMENT;
IF (FX EXISTS?) THEN (<COLOR:RED>NO)
    :CREATE FILE;
ELSE (<COLOR:GREEN>YES)
ENDIF
:1 - REGISTER INVENTORY
2 - SEARCH INVENTORY
3 - CREATE REPORT
4 - EXIT;
REPEAT
IF (OPTION = 1) THEN (<COLOR:GREEN>YES)
    :REGISTER INVENTORY;
    (<COLOR:RED>NO) ELSEIF (OPTION = 2) THEN (<COLOR:GREEN>YES)
        :SEARCH INVENTORY;
    (<COLOR:RED>NO) ELSEIF (OPTION = 3) THEN (<COLOR:GREEN>YES)
        :CREATE REPORT; 
    (<COLOR:RED>NO) ELSEIF (OPTION = 4) THEN (<COLOR:GREEN>YES)
        :EXIT;
        STOP
    ELSE (<COLOR:RED>NO)
ENDIF
@enduml