@startuml
left to right direction

header
UpSkillCobol: DeliciousSandwich
endheader

title \nBREADWICH\n



package Inventory-Management {
  usecase "UC1: Register Inventory" as UC1
  usecase "UC2: Search Inventory" as UC2
  usecase "UC3: Create Report" as UC3
}

Admin --> UC1
Admin --> UC2
Admin --> UC3

@enduml